export const copy = {
  title: "Title of this brief",
  authorLabel: "Author label for this brief",
  author: "Author of this brief",
  dateLabel: "Date label for this brief",
  versionLabel: "Version label for this brief",
  version: "Version of this brief",
  purposeLabel: "Purpose label for this brief",
  purpose: "Purpose of this brief",
  audienceLabel: "Audience label for this brief",
  audience: "Audience for this brief",
  section: "Title of this section",
  chart: "Label for this chart",
  column: "Column in this chart",
  cell: "Note for this cell",
  image: "Image for this section",
  imageUrl: "URL for this image",
  tipLabel: "Label for this pro tip",
  tip: "Recommendation in this pro tip",
  reference: "Reference for this brief",
  linkLabel: "Label for this link",
  linkUrl: "URL for this link",
  footer: "Footer for this brief",
} as const;
